### ISSUE TITLE
[Feature Request] Add Jellyseerr support

### ISSUE THREAD

**Issue by xiNeRoar** [gssariev/overr-syncerr#10]
hope jellyseerr support can be added

**Comment by gssariev** [comment]
> hope jellyseerr support can be added

From a quick glance, the webhook and API endpoints used are the same in both Overseerr and Jellyseerr; so you should be able to set it up without any problems. Just use your Jellyseerr IP and API key instead when filling out the docker compose.

**Comment by gssariev** [comment]
<img width="760" alt="Jellyseerr-test" src="https://github.com/user-attachments/assets/270b7156-418e-4926-b442-c1806ec5d69c">

Just ran a test and it's working with Jellyseerr :)

**Comment by xiNeRoar** [comment]
thank you! i will try it out.
