### ISSUE TITLE
Sync sometimes doesn't fix timing well, would like +/- adjust time commands

### ISSUE THREAD

**Issue by rjwinks** [gssariev/overr-syncerr#4]
Hello, we've been discussing on reddit already, here's a summary of my issue with some examples.

Bazaar downloaded this subtitle for this episode but it was about 2 seconds late: https://www.opensubtitles.com/en/subtitles/love-island-s11e37-1080p-hevc-x265-megusta

Another episode I tried to sync but had to manually adjust: https://www.feliratok.eu//index.php?action=letolt&felirat=1559325453

Below are my scores settings in bazaar, pretty sure I didn't touch them after set up

<img width="1102" alt="Screenshot 2024-07-12 at 2 06 26 PM" src="https://github.com/user-attachments/assets/0646bf3e-1caf-4141-8410-24b3d533e0dc">

If keywords in the "What's Wrong?" field in overseer could accept "en +2s 500ms" or "en -2s" to send the adjust time command, that would be really helpful for cases like these

**Comment by gssariev** [comment]
Thanks for sharing the subtitles and your Bazarr settings. I was successfully able to sync LI subs to the corresponding episode. I have yet to test the other subtitles; however, I tested syncing a couple of movies in my library by manually adjusting the timings by +/- a couple of minutes, and then made a call through the script to see how it will perform with the new changes. So far, so good. 

Haven't yet decided what keywords to use for this, but I appreciate the suggestion!

**Comment by gssariev** [comment]
Fixed in latest release.
